#!/bin/sh

# by Robert Campbell <rsc@indra.com>

set -e

bgcolor="white"
NARG=$#
if [ $NARG -eq 0 ]; then
	echo 1>&2 "usage: hugin-post [-b color] image.tif"
	exit 1
fi
while [ $NARG -gt 0 ]
do
	case "$1" in
		-b) bgcolor="$2"; shift;;
		*) file="$1"; break;;
	esac
	shift
done


# Now chop off the .tif
fileroot=`echo $file | awk -F'.tif' '{print $1}'`

# Let ourselves know what's happening
echo "Converting $file to ${fileroot}.jpg with a $bgcolor background."

# Call the ImageMagick utility 'convert' to do all our transformations
convert $file -background $bgcolor -layers merge -trim -quality 90 ${fileroot}.jpg
